### ISSUE TITLE
ホームのアプリ一覧で実機のタッチ操作での横スクロールが滑らかでない

### ISSUE THREAD

**Issue by dynamis** [gem-tanzanite/gem-tanzanite.github.io#1]
ホーム画面 (https://gem-tanzanite.github.io/) での横スクロールが実機のタッチ操作では滑らかでは無く delay やかくつくような感じになっている。

**Comment by ghost** [comment]
@dynamis さん現状の動作で結構滑らかかなと思いますが、一旦確認してもらえますか。mousemove毎に移動させているのでまだ改善の余地は有るかと思います。

**Comment by ashie** [comment]
確認済み
