### ISSUE TITLE
動画デモ

### ISSUE THREAD

**Issue by ashie** [gem-tanzanite/gem-tanzanite.github.io#11]
そのうち動画デモを追加したい。
以下の動画エフェクトのデモが実機でもサクサク動くので参考になりそう。

http://www.adobe.com/inspire-apps/video_effects_part2_examples-1113/examples_part2.html

**Comment by ghost** [comment]
@ashie さん ビデオ再生がマウスクリックでないと再生できない件ってどう対処しましょう？
- user_pref("dom.w3c_touch_events.enabled", 0);をやって、クリックイベントが入ってくるようにする。コンテンツは結構修正必要。
- autoplay属性追加（＆control属性削除も？)で開いたら再生開始。
- control表示を消して、HTMLでタッチに反応するコントロールUIを追加。`document.getElementById("video_player").play()`とかで対応。

**Comment by ashie** [comment]
ひとまずは

> autoplay属性追加（＆control属性削除も？)で開いたら再生開始。

で対応しておいて、余裕があれば

> control表示を消して、HTMLでタッチに反応するコントロールUIを追加。document.getElementById("video_player").play()とかで対応。

というのはどうでしょう?

**Comment by ghost** [comment]
そうですね、そうしておきます。ありがとうございます。

**Comment by ashie** [comment]
メモ:

タッチでマウスイベントを発生させるかどうかは実装依存と読める。

https://www.w3.org/TR/touch-events/#mouse-events

今のLinux版Firefoxの実装では、タッチイベントを有効化するとマウスエミュレーションは無効化され、
マウスイベントは発生しない。

**Comment by sassy** [comment]
こちらで勝手に考えた touchでvideo再生できるような修正を考えたので ( #25 )
ご参考までに。

**Comment by ashie** [comment]
動画デモ追加されたのでクローズ
