### ISSUE TITLE
時計が動かない

### ISSUE THREAD

**Issue by dynamis** [gem-tanzanite/gem-tanzanite.github.io#2]
重箱の隅を突っ込むおじさま対策

**Comment by ghost** [comment]
https://github.com/gem-tanzanite/gem-tanzanite.github.io/pull/17#issuecomment-257525827 のコメントの通り、近しいコードはありますが速度懸念からマージしていません。

**Comment by ghost** [comment]
スクロール開始時に時計を止めて、終了時に再開する？
日付だけの更新ではなんとかなるかも。

**Comment by ghost** [comment]
#36 にて修正をマージ。
