### ISSUE TITLE
写真ビューア: ランダムトランジション

### ISSUE THREAD

**Issue by dynamis** [gem-tanzanite/gem-tanzanite.github.io#3]
必須ではないですが、デモする上で写真のトランジションは選択指定もしたいですが(デフォルトでは)ランダムの方が望ましいかと思います。

**Comment by ghost** [comment]
@dynamis さん。 #14 で対応してmasterにマージ済みです。確認してよかったらクローズして下さい。

**Comment by ashie** [comment]
確認済み
