### ISSUE TITLE
小さい画面サイズに縮小表示対応できないか

### ISSUE THREAD

**Issue by dynamis** [gem-tanzanite/gem-tanzanite.github.io#38]
小さい画面サイズ (例えば 800x480 の半分で 400x 240) で表示させる時に (パフォーマンスは忘れて) コンテンツの書き直しなどをせず単に縮小表示できないか。レスポンシブデザインモードで試した限り、単純に body に対して縮小をするとトップページの読み込みは一見大丈夫だが、一部のコンテンツや合成レイヤーの生成時とかの挙動が壊れる残念状態。

```
body {
	width: calc(400px  *2) !important;
	height: calc(240px * 2) !important;
	transform: scale(0.5);
	transform-origin: 0% 0%;
}
```

**Comment by ashie** [comment]
メモ: iWaveのRZ/G1Eは480x272

**Comment by dynamis** [comment]
body { transform: scale(); } だけでは position: absolute; な要素が別座標系になっていて適用外だからカバーできないってことだと思う。body と absolute している要素だけに対してケアすればもしかしたらサクッと出来るかも。

https://drafts.csswg.org/css-transforms/#intro

> The CSS visual formatting model describes a coordinate system within each element is positioned. Positions and sizes in this coordinate space can be thought of as being expressed in pixels, starting in the origin of point with positive values proceeding to the right and down.
> 
> This coordinate space can be modified with the transform property.

**Comment by sassy** [comment]
main要素の .params_listの配置が非常に難しい。
全て相対値に直しせばなんとかなると思ったが、なかなかうまくいかない。
特にロゴ画像の指定の仕方。

**Comment by ashie** [comment]
@dynamis さんのやつをベースにしつつも、結局泥臭く調整してしまった。
iWaveのRZ/G1Eでもできれば試してみたいというだけなので、手間をかけるべきところではない。
なんでもいいからとりあえず動けば良しとする。本当に必要になったらまた見直す。

以下のCSSを追加し、フォトビューアの画像を272x272に縮小したら、大体それっぽくなる。
一箇所、グラフのクローズボタンだけなぜか実機でのみ動作していない。

```
.container {
    width:  800px;
    height: 480px;
}

.container,
#photo_nav,
.detail.temp_detail,
.detail.power_detail,
.detail.video_detail {
    transform: scale(0.6);
    transform-origin: 0% 0%;
}

.app_detail.app_home .home_ctrl_main_side .tit_inner {
    padding: .4rem .4rem 0;
}

.app_detail.app_home .home_ctrl_chart_side {
    padding: .4rem .4rem .4rem 0;
}

.app_detail.app_home .params_list {
    padding: .4rem;
}

.app_detail {
    top: 30px;
    width: 480px;
    height: 242px;
    font-size: 6px;
}

.app_detail.app_home .ctrl_btns {
    height: 112px;
}

.app_detail.app_home .chart_panel {
    height: calc(50% - 0.2rem);
}

.app_detail.app_home .ctrl_btns li span {
    padding: .2rem 0 0;
}

.app_home .param_value img {
    height: 25px;
}

.app_home .param_value {
    min-height: 20px;
}

.app_detail .param_tit {
    font-size: 8px;
}

.app_detail .param_data {
    font-size: 6px;
}

.detail.photo_detail {
    width: 600px;
    height: 272px;
}

#slider {
  width: 272px;
  height: 272px;
}
```

**Comment by ashie** [comment]
> 一箇所、グラフのクローズボタンだけなぜか実機でのみ動作していない。

タッチパネルのキャリブレーションの問題の気がする。
一生懸命つつけば、たまに願いが叶う。

**Comment by ashie** [comment]
アスペクト比がRZ/G1Mよりも少し横長なので、下がちょっとはみ出してる。
ちょっと潰れるけどこうするか?

```
    transform: scale(0.6, 0.567);
```

**Comment by ashie** [comment]
> 以下のCSSを追加し、フォトビューアの画像を272x272に縮小したら、大体それっぽくなる。

暫定対処なので画像も事前にリサイズしたものをリポジトリに入れるより実行時にスケーリングしたいのだが、flux sliderの挙動がいまいちよく分からない。272 x 272にサイズ指定するとなぜか272 x 100になる...

**Comment by ashie** [comment]
優先度は低いので、当面は事前にリサイズした画像をリポジトリに入れておく。

**Comment by ashie** [comment]
ホーム画面の枠線が潰れるので、少し太くした方が良いか。

**Comment by ashie** [comment]
#42 で暫定対応した。
