### ISSUE TITLE
動画サムネイルが縦一列になる

### ISSUE THREAD

**Issue by ashie** [gem-tanzanite/gem-tanzanite.github.io#39]
動画サムネイルはデザイン上は縦2列を想定しているが、実機では一列になってしまう。

* 画面横幅800pxに対してサムネイルの画像が400pxだから横に並べようとする
* 実機ではスクロールバーにも横幅を取られて800pxより小さいので横に2つ並べられない
* wrapする
* 横に一つになったので横幅がフィットするように縦横拡大されてしまっている。

となっている模様。

CSSを以下のようにすると2列になるが、正式にはどのように対応すべきか?

```diff
- .video_app_content .video_detail #video_nav > * { flex: 1 0 auto; }
+ .video_app_content .video_detail #video_nav > * { flex: 1 0 380px; }
```

**Comment by sassy** [comment]
上記の対応でも良いと思いますが、
トップのmain要素に合わせて、
div#video_navに ``overflow:hidden``　でスクロールバーを表示させないようにする対応はどうでしょうか？

**Comment by ashie** [comment]
ありがとうございます！マージしました！
