### ISSUE TITLE
フォトビューワーのトランジション切り替えが出来ない

### ISSUE THREAD

**Issue by ghost** [gem-tanzanite/gem-tanzanite.github.io#6]
タッチ・マウスいずれでもセレクト要素内の選択が出来ない。
Wayland版Firefox/GTK+のバグのようなので、コンテンツ側で別UIにした方が良い。

**Comment by ashie** [comment]
今気がついたのですが、マウスを接続していないとタッチで選択できるようです。
優先度下げて良さそう。

**Comment by ghost** [comment]
有線LANの下のポートにマウスを接続している状態でも選択する事が出来ますね。
もしかしてUSB3.0ポート(有線LANと同じコネクタでない方)に何か刺さってるとだめなのかな。

本Issueを確認したときは有線LANと同じポートにマウス、3.0ポートにキーボードを接続していました。
何も接続せずに起動させてコンテンツを確認したほうが良さそうですね。情報ありがとうございます。

**Comment by ghost** [comment]
#10 の修正によるものか不明ですが、マウス・キーボードを外した状態でも動かないですね。コンテンツ側での対応が必要かも。

**Comment by sassy** [comment]
<select>は
$('select').click() してもプルダウンしないので、修正は難しいかもしれません。
