### ISSUE TITLE
トップ画面のマウス・タッチへの反応エリア修正

### ISSUE THREAD

**Issue by ghost** [gem-tanzanite/gem-tanzanite.github.io#7]
HOME Control画面、フォトビューワー画面それぞれへの遷移が href にて記載してある。
これにより、トップ画面における横スクロールについてタッチ・マウスドラッグの反応出来る場所が制限されてしまっている。これを解消する。(フォトビューワー画面への遷移についてはEventHandlerも入っている）。

**Comment by ghost** [comment]
#10 により解決。

**Comment by aKosukeNagano** [comment]
#10
